Arise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recruitment.urls')),
    path('blog/', include('blog.urls')),
    path('openings/', include('openings.urls')),
    path('examination/', include('examination.urls')),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

openings/urls.py
from django.urls import path
from . import views

app_name = 'opening'

urlpatterns = [
    path('', views.all_openings, name="Openings"),
    path('<int:openings_id>/', views.opening, name="Temporary"),
]

openings/models.py
from django.db import models
from django_quill.fields import QuillField


class Openings(models.Model):
    job_title = models.CharField(max_length=128, null=False, blank=False)
    hiring_city = models.CharField(max_length=128, null=False, blank=False)
    hiring_state = models.CharField(max_length=128, null=False, blank=False)
    hiring_country = models.CharField(max_length=128, null=False, blank=False)
    zip_code = models.CharField(max_length=128, null=False, blank=False)
    salary_range_from = models.IntegerField(null=False, blank=False)
    salary_range_to = models.IntegerField(null=False, blank=False)
    job_role = models.CharField(max_length=128, null=False, blank=False)
    domain = models.CharField(max_length=128, null=False, blank=False)
    job_description = QuillField()
    experience_from_years = models.SmallIntegerField(null=False, blank=False)
    experience_to_years = models.SmallIntegerField(null=False, blank=False)
    permanent = models.BooleanField(default=True)
    posted_date = models.DateField(null=False, blank=False, auto_now_add=True)
    online = models.BooleanField(default=True)
    full_time_job = models.BooleanField(default=True)
    job_country = models.CharField(max_length=128, null=False, blank=False)
    industries = models.CharField(max_length=128, null=False, blank=False)
    job_description_file = models.FileField(upload_to='JD/')
    display = models.BooleanField(default=True)
    objects = models.manager

    def __str__(self):
        return self.job_title

openings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Openings


def all_openings(request):
    data = Openings.objects.all()
    return render(request, 'openings/openings.html', {'data': data})


def opening(request, openings_id):
    data = get_object_or_404(Openings, pk=openings_id)
    return render(request, 'openings/temporary.html', {'data': data})

templates/openings/openings.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Openings {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <style>
      .bw {
        width: fit;
      }

      .show {
        display: none;
      }

      @media screen and (max-width: 600px) {
        .bw {
          width: 100%;
          position: relative;
          right: 15px;
        }

        .show {
          display: inline;
        }

        .hide {
          display: none;
        }
      }
    </style>
    <div>
      <div class="text-center text-white mt-3 mb-5" style="background: #e14d2a">
        <h1 class="h1 text-center">
          Find your next best workplace with us- in a family like ambience.
        </h1>
        <h3 class="h5 w-50 mx-auto pb-3">
          Sorting out the best job can be tough and cracking it can be even tougher. But if you have
          it in you and dream to make your own mark, be the part of our rapidly growing team. With
          us you can experience the humane side of things.
        </h3>
      </div>
      <div class="d-flex flex-sm-row flex-column container">
{#        <div class="mt-5 pt-4 hide" style="margin-right: 5rem">#}
{#          <h5 class="h5">Filters</h5>#}
{#          <br />#}
{#          <input type="checkbox" /> Remote Jobs#}
{#          <h6 class="text-muted h6 mt-3">Job Type</h6>#}
{#          <input class="my-1" type="checkbox" /> Any#}
{#          <br />#}
{#          <input class="my-1" type="checkbox" /> Contract#}
{#          <br />#}
{#          <input class="my-1" type="checkbox" /> Full Time#}
{#          <br />#}
{#          <input class="my-1" type="checkbox" /> Permanent#}
{#          <br />#}
{#          <input class="my-1" type="checkbox" /> Work from Home <br />#}
{#          <h6 class="text-muted h6 mt-3">Country</h6>#}
{#          <input class="my-1" type="checkbox" /> India <br />#}
{#          <h6 class="text-muted h6 mt-3">Industry</h6>#}
{#          <input class="my-1" type="checkbox" /> Business Management#}
{#          <br />#}
{#        </div>#}
        <div class="w-100">
          <h1 class="h3 m-0">Join us</h1>
          <h1 class="h5 text-muted">Current Openings</h1>
{#          <div class="show my-5" data-toggle="modal" data-target="#filter-modal">🜄 Filters</div>#}
{#          <div#}
{#            class="modal fade"#}
{#            id="filter-modal"#}
{#            role="dialog"#}
{#            aria-labelledby="exampleModalLabel"#}
{#            aria-hidden="true"#}
{#          >#}
{#            <div class="modal-dialog" role="document">#}
{#              <div class="modal-content">#}
{#                <div class="modal-header">#}
{#                  <h5 class="modal-title" id="exampleModalLabel">Filters</h5>#}
{#                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">#}
{#                    <span aria-hidden="true">&times;</span>#}
{#                  </button>#}
{#                </div>#}
{#                <div class="modal-body">#}
{#                  <input type="checkbox" /> Remote Jobs#}
{#                  <h6 class="text-muted h6 mt-3">Job Type</h6>#}
{#                  <input class="my-1" type="checkbox" /> Any#}
{#                  <br />#}
{#                  <input class="my-1" type="checkbox" /> Contract#}
{#                  <br />#}
{#                  <input class="my-1" type="checkbox" /> Full Time#}
{#                  <br />#}
{#                  <input class="my-1" type="checkbox" /> Permanent#}
{#                  <br />#}
{#                  <input class="my-1" type="checkbox" /> Work from Home <br />#}
{#                  <h6 class="text-muted h6 mt-3">Country</h6>#}
{#                  <input class="my-1" type="checkbox" /> India <br />#}
{#                  <h6 class="text-muted h6 mt-3">Industry</h6>#}
{#                  <input class="my-1" type="checkbox" /> Business Management <br />#}
{#                </div>#}
{#                <div class="modal-footer">#}
{#                  <button type="button" class="btn btn-secondary" data-dismiss="modal">#}
{#                    Close#}
{#                  </button>#}
{#                  <button type="button" class="btn btn-primary">Apply Filters</button>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
          <div class="input-group mb-3 mr-3">
            <div class="d-flex flex-sm-row flex-column mt-3">
              <div class="input-group mr-3">
                <h4 class="w-100 mb-3">What</h4>
                  <label>
                      <input type="text" class="form-control" placeholder="Job title or Skill" />
                  </label>
                  <div class="input-group-append">
                  <span class="input-group-text" id="basic-addon2">&#128269;</span>
                </div>
              </div>
              <br />
              <div class="input-group mr-3">
                <h4 class="w-100 mb-3">Where</h4>
                  <label>
                      <input type="text" class="form-control" placeholder="City, state/province or Country"/>
                  </label>
                  <div class="input-group-append">
                  <span class="input-group-text" id="basic-addon2">&#128204;</span>
                </div>
              </div>
              <br />
            </div>
            <div class="mt-md-5 mt-0 bw">
              <button type="button" class="w-100 p ml-3 btn btn-warning">Search</button>
            </div>
            <div class="my-4"></div>
              {% for dt in data %}
            <div class="d-flex" style="width: 80vw">
              <div>
                <a href="{% url 'opening:Temporary' dt.id %}" class="h4 m-0 p-0 text-warning">
                  {{ dt.job_title }} - {{ dt.hiring_city }}
                </a>
                <h6 class="h6 m-0 p-0">{{ dt.hiring_city }}, {{ dt.hiring_state }}, {{ dt.hiring_country }}</h6>
                <br />
                <p>{{ dt.job_role }}</p>
              </div>
              <div class="ml-md-auto ml-auto">
                <h6 class="h6 font-weight-bold m-0 p-0">{{ dt.permanent }}</h6>
                <h6 class="h6 m-0 p-0">{{ dt.posted_date }}</h6>
                <h6 class="h6 m-0 p-0Kolkata, West Bengal, India">
                    Experience {{ dt.experience_from_years }} - {{ dt.experience_to_years }}
                </h6>
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

templates/openings/temporary.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Openings {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <style>
      .bw {
        width: fit;
      }

      .show {
        display: none;
      }

      @media screen and (max-width: 600px) {
        .bw {
          width: 100%;
          position: relative;
          right: 15px;
        }

        .show {
          display: inline;
        }

        .hide {
          display: none;
        }
      }
    </style>
    <div>
      <div class="text-center text-white mt-3 mb-5" style="background: #e14d2a">
        <h1 class="h1 text-center">{{ data.job_title }} - {{ data.hiring_city }}</h1>
        <h3 class="h5 w-50 mx-auto pb-3">{{ data.hiring_city }}, {{ data.hiring_state }}, {{ data.hiring_country }} | Posted on {{ data.posted_date }}</h3>
      </div>

      <div class="d-flex flex-sm-row flex-column container">
        <div class="w-75">
          <h3 class="h3">Job Description :</h3>
          <h5 class="h5">Job Role: {{ data.job_role }}</h5>
          <h5 class="h5">Location {{ data.hiring_city }}</h5>
          <h5 class="h5">Domain- {{ data.domain }}</h5>
          <h5 class="h5">
              {% if data.online %}
                  Online Job
              {% else %}
                  Offline Job
              {% endif %}
          </h5>
          <h5 class="h5">Job type-
              {% if data.full_time_job %}
                  Full
              {% else %}
                  Part
              {% endif %}
              time</h5>
            <h5 class="h5">
                Experience- {{ data.experience_from_years }}-{{ data.experience_to_years }} Years
            </h5>
	  <br />
          <h6 class="h6">What you will do :</h6>
          <p>
            {{ data.job_description.html|safe }}
          </p>
        </div>
        <div>
          <h4 class="h4 mt-5 mt-md-0">Job Information :</h4>
          <div class="text-muted">Salary</div>
          <div class="mt-2">{{ data.salary_range_from }} - {{ data.salary_range_to }}</div>
          <br />
          <div class="text-muted">City</div>
          <div class="mt-2">{{ data.hiring_city }}</div>
          <br />
          <div class="text-muted">State/Province</div>
          <div class="mt-2">{{ data.hiring_state }}</div>
          <br />
          <div class="text-muted">Hiring Country</div>
          <div class="mt-2">{{ data.hiring_country }}</div>
          <br />
          <div class="text-muted">Job Country</div>
          <div class="mt-2">{{ data.job_country }}</div>
          <br />
          <div class="text-muted">Industry</div>
          <div class="mt-2">{{ data.industries }}</div>
          <br />
          <div class="text-muted">Zip/Postal Code</div>
          <div class="mt-2">{{ data.zip_code }}</div>
          <br />
          <div class="text-muted">Download JD</div>
          <div class="mt-2"><a href="{{ data.job_description_file.url }}">{{ data.job_description_file.name }}</a></div>
          <br />
          <div class="text-muted">Apply in this Job</div>
          <div class="mt-2">
              <a class="btn btn-block bg-primary" href="{% url 'WalkinForm' %}">Apply</a>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>