Arise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recruitment.urls')),
    path('blog/', include('blog.urls')),
    path('openings/', include('openings.urls')),
    path('examination/', include('examination.urls')),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

openings/urls.py
from django.urls import path
from . import views

app_name = 'opening'

urlpatterns = [
    path('', views.all_openings, name="Openings"),
    path('<int:openings_id>/', views.opening, name="Temporary"),
]

templates/applicationprocess.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Life At Arise {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <div>
      <div class="">
        <h1 class="h1 text-center text-white py-2 my-5" style="background: #e14d2a">Application Process</h1>
        <div class="text-center">
          <p style="color: black; font-size: 1.2rem; line-height: 1.5" class="w-75 mx-auto">
            Arise Solution is committed to providing an excellent customer experience. To that end,
            we have created the Arise Solution Job Seeker Portal - a streamlined application process
            that takes the guesswork out of job seeking. The Arise Solution Job Seeker Portal is
            designed to save you time and energy. We have simplified the process by gathering all of
            the necessary information in one place. In just a few clicks, you will be on your way to
            finding your perfect job match. Arise Solution values your time and is committed to
            making your job search as efficient as possible. We hope you take advantage of the Arise
            Solution Job Seeker Portal and find the position that is right for you. Thank you for
            considering Arise Solution as your employment partner.
          </p>
          <img class="w-25 my-5" src="{% static 'image/application.png' %}" />
        </div>
          <button type="button" class="btn btn-primary d-flex mx-auto">Apply Here</button>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

templates/awards.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Awards and Accomplishments {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <div>
      <div class="text-center text-white h1" style="background: #e14d2a">Our Accomplishments</div>
      <div class="container my-5">
        <div class="row text-center">
          <div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_1.jpg'%}"
                alt="award_1"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div><div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_2.jpg'%}"
                alt="award_2"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div><div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_3.jpg'%}"
                alt="award_3"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div><div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_4.jpg'%}"
                alt="award_4"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div><div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_5.jpg'%}"
                alt="award_5"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div><div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_6.jpg'%}"
                alt="award_6"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div><div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_7.jpg'%}"
                alt="award_7"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div><div class="col-xl-3 col-sm-6 mb-5">
            <div style="height: 15rem" class="bg-white rounded shadow w-fit d-grid">
              <img
                src="{%static 'award_8.jpg'%}"
                alt="award_8"
                class="img-fluid px-2 mx-auto my-auto"
              />
	      <br />
              <h5 class="mt-auto mb-3">Award 1</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js?r=5426"></script>
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/ScrollTrigger.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Quantico&display=swap"
      rel="stylesheet"
    />
    <title>{% block title %} {% endblock %}</title>
    <style>
      html {
        {% comment %} font-family: "Josefin Sans", sans-serif; {% endcomment %}
        font-family: 'Quantico', sans-serif;
      }
      .achieve {
        width: 25%;
      }

      .dropdown-toggle::after {
        vertical-align: 0.1em !important;
      }

      @media only screen and (min-width: 500) {
        .achieve {
          width: none;
        }
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top">
      <div class="container-fluid">
        <a href="{% url 'Home' %}" class="navbar-brand">
          <img src="{% static 'arise_logo.jpg' %}" height="70" alt="Arise" />
        </a>
        <button
          type="button"
          class="navbar-toggler"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
            <a href="{% url 'Home' %}" class="nav-item nav-link active mr-3">Home</a>
            <a href="#" class="nav-item nav-link active mr-3">Case Studies</a>
            <a href="{% url 'blog:all_blogs' %}" class="nav-item nav-link active mr-3">Blogs</a>
          </div>
          <div class="nav-item dropdown mr-3">
            <a
              href="#"
              class="nav-link dropdown-toggle p-0 m-2"
              data-bs-toggle="dropdown"
              style="color: black"
              >Our Services</a
            >
            <div class="dropdown-menu">
              <a href="{% url 'Apprenticeship' %}" class="dropdown-item">Apprenticeship</a>
              <hr class="my-2" />
              <a href="{% url 'BulkRecruit' %}" class="dropdown-item">Bulk Recruitment</a>
              <hr class="my-2" />
              <a href="{% url 'ContractStaff' %}" class="dropdown-item">Contract Staffing</a>
              <hr class="my-2" />
              <a href="{% url 'EmployeeLease' %}" class="dropdown-item">Employee Leasing</a>
              <hr class="my-2" />
              <a href="{% url 'HireTrainDeploy' %}" class="dropdown-item">Hire-Train-Deploy</a>
              <hr class="my-2" />
              <a href="{% url 'ItStaff' %}" class="dropdown-item">IT Staffing</a>
              <hr class="my-2" />
              <a href="{% url 'Leadership' %}" class="dropdown-item">Leadership Hiring</a>
              <hr class="my-2" />
              <a href="{% url 'Payroll' %}" class="dropdown-item">Payroll & Compliance</a>
              <hr class="my-2" />
              <a href="{% url 'PermStaff' %}" class="dropdown-item">Permanent/Temporary Staffing</a>
              <hr class="my-2" />
              <a href="{% url 'Turnkey' %}" class="dropdown-item">TurnKey Projects</a>
            </div>
          </div>
          <div class="nav-item dropdown mr-3">
            <a
              href="#"
              class="nav-link dropdown-toggle p-0 m-2"
              data-bs-toggle="dropdown"
              style="color: black"
              >About Arise Solutions</a
            >
            <div class="dropdown-menu">
              <a href="{% url 'ApplicationProcess' %}" class="dropdown-item">Application Process</a>
              <hr class="my-2" />
              <a href="{% url 'LifeAtArise' %}" class="dropdown-item">Life at Arise</a>
              <hr class="my-2" />
              <a href="{% url 'WhyAriseSolution' %}" class="dropdown-item">Why Arise Solutions</a>
              <hr class="my-2" />
              <a href="{% url 'Awards' %}" class="dropdown-item">Awards & Accomplishments</a>
              <hr class="my-2" />
              <a href="{% url 'Careers' %}" class="dropdown-item">Careers at Arise</a>
            </div>
          </div>
          <div class="navbar-nav">
            <a href="{% url 'ContactUs' %}" class="nav-item nav-link active mr-3">Contact Us</a>
            <a href="{% url 'opening:Openings' %}" class="nav-item nav-link active mr-3"
              >Current Openings</a
            >
            <a href="{% url 'WalkinForm' %}" class="nav-item nav-link active mr-3"
              >Walk in Form</a
            >
          </div>
          <div class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <a href="{% url 'Logout' %}" class="nav-item nav-link" style="color: black">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-box-arrow-right"
                viewBox="0 0 16 16"
              >
                <path
                  fill-rule="evenodd"
                  d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"
                ></path>
                <path
                  fill-rule="evenodd"
                  d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"
                ></path>
              </svg>
            </a>
            {% else %}
            <a href="{% url 'Login' %}" class="nav-item nav-link" style="color: black">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-box-arrow-left"
                viewBox="0 0 16 16"
              >
                <path
                  fill-rule="evenodd"
                  d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"
                ></path>
                <path
                  fill-rule="evenodd"
                  d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"
                ></path>
              </svg>
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <footer
      class="py-5 mt-5 bg-dark"
      style="background-image: linear-gradient(bottom, #000000, #2d3436)"
    >
      <div class="container">
        <div class="row">
          <div class="col-md-3 mb-4 brand">
            <h1 style="color: white">Brand</h1>
            <br />
            <ul class="brand-list">
              <li><a href="{% url 'Home' %}" class="text-muted text-decoration-none">Home</a></li>
              <br />
              <li><a href="/about/" class="text-muted text-decoration-none">Arise Solutions</a></li>
              <br />
              <li>
                <a href="/cart/" class="text-muted text-decoration-none">Rewards & Recognition</a>
              </li>
              <br />
              <li>
                <a href="/shippingandreturns/" class="text-muted text-decoration-none"
                  >Achievements</a
                >
              </li>
            </ul>
          </div>
          <div class="col-md-3 mb-4 contact-us">
            <h1 style="color: white">Contact Us</h1>
            <p class="text-muted my-3">
              <a
                href="mailto: info@arisesolution.com"
                style="text-decoration: underline"
                class="text-muted"
              >
                <span>Email</span>
              </a>
              <br />
              <br />
              <a href="tel: +919099922307">
                <span style="text-decoration: underline" class="text-muted">Whatsapp</span>
              </a>
            </p>
          </div>

          <div class="col-md-6 mb-4 d-flex flex-column">
            <h1 style="color: white" class="mr-auto mb-2">Sign up to our newsletter</h1>
            <br />
            <p class="text-left text-muted mb-2">
              Be the first to know about our new collections and special offers
            </p>
            <br />
            <div class="newsletter mr-auto">
              <form method="POST" action="{% url 'add_mail' %}" class="d-flex">
                {% csrf_token %} {{ my_form.subscribe }}
                <button type="submit" class="btn btn-outline-light">Subscribe</button>
              </form>
            </div>
          </div>
          <div class="col-md-2 mb-4 d-flex flex-column">
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3672.0441550427918!2d72.5405593153495!3d23.02215092212016!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x395e84db49432a1f%3A0x90dd3f4fcf90feae!2sArise%20Solution!5e0!3m2!1sen!2sin!4v1668341256989!5m2!1sen!2sin"
              class="mt-3"
              width="150"
              height="100"
              style="border: 0"
              allowfullscreen=""
              loading="lazy"
              referrerpolicy="no-referrer-when-downgrade"
            ></iframe>
          </div>
          <div class="col-md-4 mb-4 d-flex flex-column justify-content-center">
            <h1 class="text-muted">
              Arise Solution , 502 (West Wing), 5th Floor , Venus Stratum, @ Venus Grounds,
              Nehrunagar Road , Ahmedabad 380015.
            </h1>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

templates/bulkrecruit.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Bulk Recruit {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <div>
      <div class="">
        <h1 class="h1 text-center text-white py-2 my-5" style="background: #e14d2a">
          Bulk Recruiting at Arise
        </h1>
        <div class="text-center">
          <p style="color: black; font-size: 1.2rem; line-height: 1.5" class="w-75 mx-auto">
            In the recruitment industry, volume hiring refers to the process of recruiting a large
            number of candidates in a short period of time. This is often done in order to fill a
            high-demand role or to staff a new location. In order to successfully complete a volume
            hire, recruiters must have a strong understanding of the needs of the client and be able
            to identify suitable candidates quickly. They must also be able to manage a large pool
            of candidates and keep track of their progress throughout the recruitment process. While
            volume hiring can be challenging, it can also be very rewarding for both recruiters and
            clients. When done correctly, it can help businesses to quickly fill critical roles and
            grow their workforce. Bulk hiring can be a daunting task for any organization. From
            sourcing to screening to scheduling interviews, the process canTake up a lot of time and
            resources. Arise Solution offers Bulk Recruitment Services that can help companies save
            time and money. We have a global network of talent sourcers and recruiters who can help
            you quickly fill open positions. Our Bulk Recruitment Service includes: • Sourcing: We
            will identify and engage candidates that match your specific job requirements. •
            Screening: We will screen candidates using our proven methodology that assesses skills,
            experience, and motivation. • Scheduling: We will coordinate interviews and provide
            feedback to help you make the best hiring decisions. Arise Solution has the experience
            and expertise to help you with all your volume hiring needs. Contact us today to learn
            more about our Bulk Recruitment Service.
          </p>
          <img style="width: 40%" class="my-5" src="{% static 'recruit.jpeg' %}" />
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

templates/contactus.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Contact Us {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/contactus.css' %}" />
    <section class="gradient-form" style="background-color: #eee">
      <div class="container" style="padding-top: 100px">
        <div class="row d-flex justify-content-center align-items-center">
          <div class="col-xl-10">
            <div class="card rounded-3 text-black">
              <div class="row g-0">
                <div class="col-lg-6">


                  <div class="card-body p-md-5 mx-md-4">
                    <div class="text-center">
                      <img src="{% static 'arise_logo.jpg' %}" style="width: 185px" alt="logo" />
                    </div>
                    <br />
                      {% if error %}
                      <div class="alert alert-danger" role="alert">{{ error }}</div>
                      {% endif %}
                    <form method="post" action="{% url 'ContactUs' %}">
                        {% csrf_token %}
                      <div class="form-outline mb-4 form-group">
                        <label class="form-label" for="name">Name</label>
                        <input type="text" id="name" name="name" class="form-control" />
                      </div>

                      <div class="form-outline mb-4 form-group">
                        <label class="form-label" for="email">Email</label>
                        <input type="email" id="email" name="email" class="form-control" />
                      </div>

                      <div class="form-outline mb-4 form-group">
                        <label class="form-label" for="subject">Subject</label>
                        <input type="text" id="subject" name="subject" class="form-control" />
                      </div>
                      <div class="form-outline mb-4 form-group">
                        <label class="form-label" for="message">Message</label>
                        <input type="text" id="message" name="message" class="form-control" />
                      </div>

                        <button type="submit" class="btn btn-block fa-lg text-white bg-primary mb-3">Send</button>
                    </form>
                  </div>





                </div>
                <div class="col-lg-6 d-flex align-items-center" style="background: #e14d2a">
                  <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                    <p class="mb-4 lead" style="font-size: 2rem">
                      We are more than just a Company...
                    </p>
                    <p class="small mb-0 lead text-justify" style="line-height: 1.5">
                      At Arise Solution, we are the leading provider of recruitment and staffing
                      services. We specialize in finding the right people for the right job, and we
                      have a proven track record of success. If you are looking for a new employee
                      or if you are looking for a new job, we have a team of experienced
                      professionals who are experts at matching people with the right jobs. We offer
                      a variety of services, including job placement, resume writing, and career
                      counseling. We also provide training and development programs to help
                      employees improve their skills and advance their careers.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}
  </body>
</html>

templates/contractstaff.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Contract Staffing {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <div>
      <div class="">
        <h1 class="h1 text-center text-white py-2 my-5" style="background: #e14d2a">
          What's Contract Staffing?
        </h1>
        <div class="text-center">
          <p style="color: black; font-size: 1.2rem; line-height: 1.5" class="w-75 mx-auto">
            Contract staffing is a type of recruitment in which candidates are hired to work for a
            specific period of time, usually on a project basis. The length of the contract can vary
            depending on the needs of the employer, but it is typically for a period of six months
            to one year. After the contract period ends, the employee is typically no longer
            employed by the company. Contract staffing can be an advantageous way for employers to
            find talented workers for specific projects without having to commit to a long-term
            employment relationship. It can also be beneficial for employees who are looking for
            flexibility or who only want to work on a short-term basis. However, contract staffing
            can also be less stable than traditional employment arrangements and may not provide
            employees with the same benefits, such as health insurance and retirement savings plans.
          </p>
        </div>
        <h1 class="h1 text-center text-white bg-primary py-2 my-5">Contract Staffing at Arise</h1>
        <div class="text-center">
          <p style="color: black; font-size: 1.2rem; line-height: 1.5" class="w-75 mx-auto mt-5">
            At Arise Solutions, we offer the best staffing services that cater to both short-term as
            well as project-based staffing requirements of our clients. We strive to make the costs
            of employee administration as less as we can. But, most importantly, it is our aim to
            add value to our client businesses with temp staffing services, which they may even
            decide to absorb into their company rolls in the future. According to your personnel
            requirement, in terms of duration, qualifications, skill set, or specific project needs
            and more, you will find Arise to meet your staffing requirements in full. Outsourcing
            your contract staffing needs to Arise Solutions consultants will certainly leave you
            more time to concentrate on your core business, while saving you a lot of money and
            resources. We are confident that our team of highly skilled and experienced
            professionals will be able to deliver the results that you are looking for. So why not
            get in touch with us today and let us show you what we can do?
          </p>
          <img style="width: 40%" class="mb-5" src="{% static 'contract.jpg' %}" />
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

templates/hiretraindeploy.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Hire, Train and Deploy {% endblock %}</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <div>
      <div class="">
        <h1 class="h1 text-center text-white py-2 my-5" style="background: #e14d2a">
          Hiring, Training and Deploying made easy via Arise
        </h1>
        <div class="text-center">
          <p style="color: black; font-size: 1.2rem; line-height: 1.5" class="w-75 mx-auto">
            Arise Solution is a leading provider of Recruitment & Staffing Services. We are
            committed to providing the highest quality of service to our clients. At Arise Solution,
            we understand that every business has unique staffing needs. That's why we offer a
            comprehensive range of recruitment and staffing services. We can help you find the right
            candidates for any role, and our training and deployment services ensure that they have
            the skills and knowledge required to succeed in their new positions. Whether you're
            looking for a temporary employee to cover a maternity leave or a permanent staff member
            to fill a critical role, we can help. As part of the Hire-Train-Deploy service, we hire,
            train and deploy employees as per their exact specification of our client. For example,
            if you are looking for a SEO specialist, we will hire, train the candidate on SEO
            skillset and deploy it to you in the given timeframe. We have a team of experienced and
            qualified professionals who are experts in their respective fields and we are confident
            that we can provide you with the best possible service. Contact us today to discuss your
            requirements. Thank you.
          </p>
          <img style="width: 40%" class="my-5" src="{% static 'train.jpg' %}" />
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>